site_name: Camelina
site_url: https://grow.regenrate.com
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides
  palette: 
    primary: custom
    accent: deep orange
  logo: assets/logo.svg
  favicon: images/favicon.png
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
plugins:
  - social:
      cards_layout_options:
        background_color: "#34312c"
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
        - locale: es
          name: Español
          build: true
        - locale: pt
          name: Português
          build: true
        - locale: nl
          name: Nederlands
          build: true
        - locale: de
          name: Deutsch
          build: true
extra:
  analytics:
    provider: google
    property: G-YBTSEJ527G
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make grow.regenrate.com  better.
    
copyright: Copyright &copy; 2024 RegenRate
