site_name: Camelina
site_url: https://regenrate.org/camelina
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides
  palette: 
    primary: custom
    accent: custom
  logo: assets/logo.svg
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
# extra:
  # alternate:
  #   - name: English
  #     link: /en/
  #     lang: en
  #   - name: Deutsch
  #     link: /de/
  #     lang: de
  #   - name: Español
  #     link: /es/
  #     lang: es
  #   - name: Français
  #     link: /fr/
  #     lang: fr
  # generator: false
plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true

copyright: Copyright &copy; 2024 RegenRate