site_name: Camelina
site_url: https://regenrate.org/camelina
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides
  palette: 
    primary: custom
    accent: custom
  logo: assets/logo.svg
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Deutsch
      link: /de/
      lang: de
    - name: Español
      link: /es/
      lang: es
    - name: Français
      link: /fr/
      lang: fr
plugins:
  - search